/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LegislatureService } from "../legislature.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LegislatureCreateInput } from "./LegislatureCreateInput";
import { Legislature } from "./Legislature";
import { LegislatureFindManyArgs } from "./LegislatureFindManyArgs";
import { LegislatureWhereUniqueInput } from "./LegislatureWhereUniqueInput";
import { LegislatureUpdateInput } from "./LegislatureUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LegislatureControllerBase {
  constructor(
    protected readonly service: LegislatureService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Legislature })
  @nestAccessControl.UseRoles({
    resource: "Legislature",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLegislature(
    @common.Body() data: LegislatureCreateInput
  ): Promise<Legislature> {
    return await this.service.createLegislature({
      data: data,
      select: {
        createdAt: true,
        description: true,
        establishedDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Legislature] })
  @ApiNestedQuery(LegislatureFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Legislature",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async legislatures(@common.Req() request: Request): Promise<Legislature[]> {
    const args = plainToClass(LegislatureFindManyArgs, request.query);
    return this.service.legislatures({
      ...args,
      select: {
        createdAt: true,
        description: true,
        establishedDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Legislature })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Legislature",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async legislature(
    @common.Param() params: LegislatureWhereUniqueInput
  ): Promise<Legislature | null> {
    const result = await this.service.legislature({
      where: params,
      select: {
        createdAt: true,
        description: true,
        establishedDate: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Legislature })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Legislature",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLegislature(
    @common.Param() params: LegislatureWhereUniqueInput,
    @common.Body() data: LegislatureUpdateInput
  ): Promise<Legislature | null> {
    try {
      return await this.service.updateLegislature({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          establishedDate: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Legislature })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Legislature",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLegislature(
    @common.Param() params: LegislatureWhereUniqueInput
  ): Promise<Legislature | null> {
    try {
      return await this.service.deleteLegislature({
        where: params,
        select: {
          createdAt: true,
          description: true,
          establishedDate: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
