/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HomelessIndividualService } from "../homelessIndividual.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HomelessIndividualCreateInput } from "./HomelessIndividualCreateInput";
import { HomelessIndividual } from "./HomelessIndividual";
import { HomelessIndividualFindManyArgs } from "./HomelessIndividualFindManyArgs";
import { HomelessIndividualWhereUniqueInput } from "./HomelessIndividualWhereUniqueInput";
import { HomelessIndividualUpdateInput } from "./HomelessIndividualUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HomelessIndividualControllerBase {
  constructor(
    protected readonly service: HomelessIndividualService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HomelessIndividual })
  @nestAccessControl.UseRoles({
    resource: "HomelessIndividual",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHomelessIndividual(
    @common.Body() data: HomelessIndividualCreateInput
  ): Promise<HomelessIndividual> {
    return await this.service.createHomelessIndividual({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HomelessIndividual] })
  @ApiNestedQuery(HomelessIndividualFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HomelessIndividual",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async homelessIndividuals(
    @common.Req() request: Request
  ): Promise<HomelessIndividual[]> {
    const args = plainToClass(HomelessIndividualFindManyArgs, request.query);
    return this.service.homelessIndividuals({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HomelessIndividual })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomelessIndividual",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async homelessIndividual(
    @common.Param() params: HomelessIndividualWhereUniqueInput
  ): Promise<HomelessIndividual | null> {
    const result = await this.service.homelessIndividual({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HomelessIndividual })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomelessIndividual",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHomelessIndividual(
    @common.Param() params: HomelessIndividualWhereUniqueInput,
    @common.Body() data: HomelessIndividualUpdateInput
  ): Promise<HomelessIndividual | null> {
    try {
      return await this.service.updateHomelessIndividual({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HomelessIndividual })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomelessIndividual",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHomelessIndividual(
    @common.Param() params: HomelessIndividualWhereUniqueInput
  ): Promise<HomelessIndividual | null> {
    try {
      return await this.service.deleteHomelessIndividual({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
