/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExerciseCountService } from "../exerciseCount.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExerciseCountCreateInput } from "./ExerciseCountCreateInput";
import { ExerciseCount } from "./ExerciseCount";
import { ExerciseCountFindManyArgs } from "./ExerciseCountFindManyArgs";
import { ExerciseCountWhereUniqueInput } from "./ExerciseCountWhereUniqueInput";
import { ExerciseCountUpdateInput } from "./ExerciseCountUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExerciseCountControllerBase {
  constructor(
    protected readonly service: ExerciseCountService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExerciseCount })
  @nestAccessControl.UseRoles({
    resource: "ExerciseCount",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createExerciseCount(
    @common.Body() data: ExerciseCountCreateInput
  ): Promise<ExerciseCount> {
    return await this.service.createExerciseCount({
      data: {
        ...data,

        exerciseSession: data.exerciseSession
          ? {
              connect: data.exerciseSession,
            }
          : undefined,
      },
      select: {
        count: true,
        createdAt: true,

        exerciseSession: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExerciseCount] })
  @ApiNestedQuery(ExerciseCountFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExerciseCount",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async exerciseCounts(
    @common.Req() request: Request
  ): Promise<ExerciseCount[]> {
    const args = plainToClass(ExerciseCountFindManyArgs, request.query);
    return this.service.exerciseCounts({
      ...args,
      select: {
        count: true,
        createdAt: true,

        exerciseSession: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExerciseCount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExerciseCount",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async exerciseCount(
    @common.Param() params: ExerciseCountWhereUniqueInput
  ): Promise<ExerciseCount | null> {
    const result = await this.service.exerciseCount({
      where: params,
      select: {
        count: true,
        createdAt: true,

        exerciseSession: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExerciseCount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExerciseCount",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateExerciseCount(
    @common.Param() params: ExerciseCountWhereUniqueInput,
    @common.Body() data: ExerciseCountUpdateInput
  ): Promise<ExerciseCount | null> {
    try {
      return await this.service.updateExerciseCount({
        where: params,
        data: {
          ...data,

          exerciseSession: data.exerciseSession
            ? {
                connect: data.exerciseSession,
              }
            : undefined,
        },
        select: {
          count: true,
          createdAt: true,

          exerciseSession: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExerciseCount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExerciseCount",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExerciseCount(
    @common.Param() params: ExerciseCountWhereUniqueInput
  ): Promise<ExerciseCount | null> {
    try {
      return await this.service.deleteExerciseCount({
        where: params,
        select: {
          count: true,
          createdAt: true,

          exerciseSession: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
