/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExecutiveService } from "../executive.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExecutiveCreateInput } from "./ExecutiveCreateInput";
import { Executive } from "./Executive";
import { ExecutiveFindManyArgs } from "./ExecutiveFindManyArgs";
import { ExecutiveWhereUniqueInput } from "./ExecutiveWhereUniqueInput";
import { ExecutiveUpdateInput } from "./ExecutiveUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExecutiveControllerBase {
  constructor(
    protected readonly service: ExecutiveService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Executive })
  @nestAccessControl.UseRoles({
    resource: "Executive",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createExecutive(
    @common.Body() data: ExecutiveCreateInput
  ): Promise<Executive> {
    return await this.service.createExecutive({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        termEndDate: true,
        termStartDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Executive] })
  @ApiNestedQuery(ExecutiveFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Executive",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async executives(@common.Req() request: Request): Promise<Executive[]> {
    const args = plainToClass(ExecutiveFindManyArgs, request.query);
    return this.service.executives({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        termEndDate: true,
        termStartDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Executive })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Executive",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async executive(
    @common.Param() params: ExecutiveWhereUniqueInput
  ): Promise<Executive | null> {
    const result = await this.service.executive({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        termEndDate: true,
        termStartDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Executive })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Executive",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateExecutive(
    @common.Param() params: ExecutiveWhereUniqueInput,
    @common.Body() data: ExecutiveUpdateInput
  ): Promise<Executive | null> {
    try {
      return await this.service.updateExecutive({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          termEndDate: true,
          termStartDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Executive })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Executive",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExecutive(
    @common.Param() params: ExecutiveWhereUniqueInput
  ): Promise<Executive | null> {
    try {
      return await this.service.deleteExecutive({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          termEndDate: true,
          termStartDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
