/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AdoptionRequest } from "./AdoptionRequest";
import { AdoptionRequestCountArgs } from "./AdoptionRequestCountArgs";
import { AdoptionRequestFindManyArgs } from "./AdoptionRequestFindManyArgs";
import { AdoptionRequestFindUniqueArgs } from "./AdoptionRequestFindUniqueArgs";
import { DeleteAdoptionRequestArgs } from "./DeleteAdoptionRequestArgs";
import { AdoptionRequestService } from "../adoptionRequest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AdoptionRequest)
export class AdoptionRequestResolverBase {
  constructor(
    protected readonly service: AdoptionRequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AdoptionRequest",
    action: "read",
    possession: "any",
  })
  async _adoptionRequestsMeta(
    @graphql.Args() args: AdoptionRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AdoptionRequest])
  @nestAccessControl.UseRoles({
    resource: "AdoptionRequest",
    action: "read",
    possession: "any",
  })
  async adoptionRequests(
    @graphql.Args() args: AdoptionRequestFindManyArgs
  ): Promise<AdoptionRequest[]> {
    return this.service.adoptionRequests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AdoptionRequest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AdoptionRequest",
    action: "read",
    possession: "own",
  })
  async adoptionRequest(
    @graphql.Args() args: AdoptionRequestFindUniqueArgs
  ): Promise<AdoptionRequest | null> {
    const result = await this.service.adoptionRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AdoptionRequest)
  @nestAccessControl.UseRoles({
    resource: "AdoptionRequest",
    action: "delete",
    possession: "any",
  })
  async deleteAdoptionRequest(
    @graphql.Args() args: DeleteAdoptionRequestArgs
  ): Promise<AdoptionRequest | null> {
    try {
      return await this.service.deleteAdoptionRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
