/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HomelessPerson } from "./HomelessPerson";
import { HomelessPersonCountArgs } from "./HomelessPersonCountArgs";
import { HomelessPersonFindManyArgs } from "./HomelessPersonFindManyArgs";
import { HomelessPersonFindUniqueArgs } from "./HomelessPersonFindUniqueArgs";
import { DeleteHomelessPersonArgs } from "./DeleteHomelessPersonArgs";
import { HomelessPersonService } from "../homelessPerson.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => HomelessPerson)
export class HomelessPersonResolverBase {
  constructor(
    protected readonly service: HomelessPersonService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "HomelessPerson",
    action: "read",
    possession: "any",
  })
  async _homelessPeopleMeta(
    @graphql.Args() args: HomelessPersonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [HomelessPerson])
  @nestAccessControl.UseRoles({
    resource: "HomelessPerson",
    action: "read",
    possession: "any",
  })
  async homelessPeople(
    @graphql.Args() args: HomelessPersonFindManyArgs
  ): Promise<HomelessPerson[]> {
    return this.service.homelessPeople(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => HomelessPerson, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "HomelessPerson",
    action: "read",
    possession: "own",
  })
  async homelessPerson(
    @graphql.Args() args: HomelessPersonFindUniqueArgs
  ): Promise<HomelessPerson | null> {
    const result = await this.service.homelessPerson(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => HomelessPerson)
  @nestAccessControl.UseRoles({
    resource: "HomelessPerson",
    action: "delete",
    possession: "any",
  })
  async deleteHomelessPerson(
    @graphql.Args() args: DeleteHomelessPersonArgs
  ): Promise<HomelessPerson | null> {
    try {
      return await this.service.deleteHomelessPerson(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
